Algoritmo "questionario"
// Disciplina   : Portugol
// Descrição   : Questionário
// Autor(a)    : Gabriel Lisboa
// Data atual  : 03/03/2025
Var
// Variáveis
nome: caractere
idade: inteiro

Inicio
// Inicio das Perguntas
EscrevaL ("Qual o seu nome?")
leia (nome)
EscrevaL ("Qual é sua idade?")
leia (idade)


// Inicio das respostas
EscrevaL ("Resumo:")
EscrevaL ("Seu nome é ", (nome))
EscrevaL ("Sua idade é: ", (idade))
Fimalgoritmo